### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by agraver** [konsumer/rollup-plugin-jsx#1]
Plugin fails when transpiling JSX components that have "." in their name

i.e. <Dropdown.Menu>

**Comment by konsumer** [comment]
I am going to deprecate, in favor of using buble or babel to do the transform. I originally made this project for buble, before JSX support went in. have a look at [/buble-react-rollup-starter](https://github.com/yamafaktory/buble-react-rollup-starter) for a great example of usage.
