### ISSUE TITLE
When reacting to create a component using a class, it is not well supported.

### ISSUE THREAD

**Issue by sbfkcel** [konsumer/rollup-plugin-jsx#2]
When reacting to create a component using a class, it is not well supported.
```javascript
import React from 'react'
import ReactDom from 'react-dom'

class Clock extends React.Component {
  render(){
    <div>Test</div>
  }
}

ReactDom.render(
  <Clock/>,
  document.getElementById('app')
)
```

**Comment by konsumer** [comment]
As it says in README:

I originally made this project for buble, before JSX support went in. have a look at [/buble-react-rollup-starter](https://github.com/yamafaktory/buble-react-rollup-starter) for a great example of usage without this plugin.
